USE `terraform`;

/*Data for the table `cloud_providers` */

insert  into `cloud_providers`(`id`,`display_name`,`name`,`secret_id`,`secret_key`,`region`,`zone`,`plugin_source`,`extend_info`,`provider_property`,`is_init`,`created_time`,`updated_time`,`deleted_time`,`enabled`,`is_deleted`) values
('21fd34b382d844c4a2fe8acdf8ad75f0','阿里云','alicloud','xxxx','xxxx',NULL,NULL,NULL,'{}','{\"region\": \"region\", \"secret_key\": \"secret_key\", \"secret_id\": \"access_key\"}',1,'2021-01-22 10:56:36','2021-01-22 10:56:36',NULL,1,0),
('73aa4d40248849c48cb0fcde88d1d1d1','腾讯云','tencentcloud','xxxx','xxxx',NULL,NULL,NULL,'{}','{\"region\": \"region\", \"secret_key\": \"secret_key\", \"secret_id\": \"secret_id\"}',1,'2021-01-13 11:15:56','2021-01-13 11:15:56',NULL,1,0);

/*Data for the table `config` */

insert  into `config`(`id`,`provider`,`resource`,`property`,`value_config`,`is_locked`,`created_time`,`updated_time`,`deleted_time`,`enabled`,`is_deleted`) values
('09f9682305484958bf54fe53270a7f39','alicloud','security_group_rule','policy','{\"DROP\": \"drop\", \"ACCEPT\": \"accept\"}',0,'2021-01-29 15:11:25','2021-01-29 15:11:25',NULL,1,0),
('0f490f44980448aeb61efca2b0120107','alicloud','mysql','engine','{\"mysql\": \"MySQL\"}',0,'2021-01-25 16:09:26','2021-01-25 16:09:26',NULL,1,0),
('191ca26f942a42b598636cf01b8a20ce','alicloud','instance','power_action','{\"start\": \"Running\", \"stop\": \"Stopped\"}',0,'2021-01-25 15:24:48','2021-01-25 15:24:48',NULL,1,0),
('1e5ee3d572204bc4aaa96e57256f0386','alicloud','security_group_rule','ports','{\"10000\": \"10000/10000\", \"80\": \"80/80\", \"8000-9000\": \"8000/9000\", \"8080\": \"8080/8080\"}',0,'2021-01-29 15:11:34','2021-01-29 15:11:34',NULL,1,0),
('20d0c747c96040afbeab159a2f5e696c','tencentcloud','subnet','cidr','{\"subnet_22\": \"10.1.2.0/24\", \"subnet_21\": \"10.1.1.0/24\", \"subnet_20\": \"10.0.20.0/24\", \"subnet_1\": \"10.0.1.0/24\"}',0,'2021-01-12 19:43:17','2021-01-21 16:52:09',NULL,1,0),
('29207d072f0f4edb81540cf947b6b1cf','tencentcloud','zone','zone','{\"guangzhou4\": \"ap-guangzhou-4\", \"guangzhou3\": \"ap-guangzhou-3\"}',0,'2021-01-12 19:45:23','2021-01-12 19:45:23',NULL,1,0),
('2ef73d2139054fb99ebccd7bdbb2ff77','tencentcloud','instance','disk_type','{\"normal_disk\": \"CLOUD_PREMIUM\"}',0,'2021-01-22 16:50:42','2021-01-22 16:50:42',NULL,1,0),
('35bb9c075a254e1eb54e8d9c42e817ef','alicloud','instance','image','{\"linux_centos_7.7\": \"centos_7_7_x64_20G_alibase_20200426.vhd\"}',0,'2021-01-25 16:58:27','2021-01-25 16:58:27',NULL,1,0),
('650e96b3687d453e900151ab327a0451','alicloud','zone','zone','{\"guangzhou1\": \"cn-guangzhou-a\", \"guangzhou2\": \"cn-guangzhou-b\"}',0,'2021-01-22 14:44:33','2021-01-22 14:44:33',NULL,1,0),
('6718f4fe5aa44e50b599ab6a7c1a8c41','alicloud','vpc','cidr','{\"vpc_1\": \"10.1.0.0/16\", \"vpc_0\": \"10.0.0.0/16\"}',0,'2021-01-21 19:40:13','2021-01-21 19:40:13',NULL,1,0),
('9e70671e06f345d2872c339bc42a71c4','tencentcloud','region','region','{\"guangzhou\": \"ap-guangzhou\"}',0,'2021-01-13 10:19:34','2021-01-13 10:19:34',NULL,1,0),
('a1d7ed23ee964ec1a9e57f7374534a4a','alicloud','object_storage','acl','{\"true\": \"public-read\", \"false\": \"private\"}',0,'2021-01-29 15:19:29','2021-01-29 15:19:29',NULL,1,0),
('c2046e3418df492da3e6beff4d43c606','alicloud','region','region','{\"guangzhou\": \"cn-guangzhou\"}',0,'2021-01-22 14:46:06','2021-01-22 14:46:06',NULL,1,0),
('c63f9333d4994091998e723a8ae15520','tencentcloud','object_storage','acl','{\"true\": \"public-read\", \"false\": \"private\"}',0,'2021-01-29 15:19:39','2021-01-29 15:19:39',NULL,1,0),
('c92ef007d24943179cf552410171b109','tencentcloud','instance','power_action','{\"start\": \"true\", \"stop\": \"false\"}',0,'2021-01-22 17:43:34','2021-01-22 17:43:34',NULL,1,0),
('db5af6d4408242bb835300b7fd968bb3','tencentcloud','lb','network_type','{\"INTERNAL\": \"intranet\", \"OPEN\": \"internet\"}',0,'2021-01-29 15:21:55','2021-01-29 15:21:55',NULL,1,0),
('de1105c827a64ebe8f342517348bbd92','tencentcloud','instance','image','{\"linux_centos_7.6_x64\": \"img-9qabwvbn\", \"linux_centos_7.8_x64\": \"img-3la7wgnt\"}',0,'2021-01-22 16:51:05','2021-01-22 16:51:05',NULL,1,0),
('ed329c71020f490491c2d5c5b9447077','alicloud','subnet','cidr','{\"subnet_22\": \"10.1.2.0/24\", \"subnet_21\": \"10.1.1.0/24\", \"subnet_20\": \"10.0.20.0/24\", \"subnet_1\": \"10.0.1.0/24\"}',0,'2021-01-21 19:40:01','2021-01-21 19:40:01',NULL,1,0),
('ef77e14d64644357978d3036480e2684','alicloud','security_group_rule','ip_protocol','{\"UDP\": \"udp\", \"ICMP\": \"icmp\", \"TCP\": \"tcp\"}',0,'2021-01-29 15:11:43','2021-01-29 15:11:43',NULL,1,0),
('f28a57cd7d1b46448109f347b39e6124','tencentcloud','instance','instance_type','{\"1C-2G-01\": \"S5.SMALL2\", \"1C-4G-01\": \"S5.SMALL4\"}',0,'2021-01-22 16:50:53','2021-01-22 16:50:53',NULL,1,0),
('f5be05e69af540fb96440e0a403027db','tencentcloud','vpc','cidr','{\"vpc_1\": \"10.1.0.0/16\", \"vpc_0\": \"10.0.0.0/16\"}',0,'2021-01-13 10:05:52','2021-01-13 10:05:52',NULL,1,0);

/*Data for the table `instance_type` */

insert  into `instance_type`(`id`,`provider_id`,`provider`,`name`,`origin_name`,`cpu`,`memory`,`network`,`extend_info`,`define_json`,`status`,`result_json`,`created_time`,`updated_time`,`deleted_time`,`enabled`,`is_deleted`) values
('2c3308779aab448ca38b732cd05740b3','21fd34b382d844c4a2fe8acdf8ad75f0','alicloud','1C-1024M','ecs.s6-c1m1.small',1,1024,NULL,'{}',NULL,NULL,NULL,'2021-01-25 17:57:23','2021-01-25 17:57:23',NULL,1,0),
('a814c4b2400e43f89d30cd167a9cf9c3','73aa4d40248849c48cb0fcde88d1d1d1','tencentcloud','1C-2G','S5.SMALL2',1,2,'1.5Gbps  --  25万PPS','{}',NULL,NULL,NULL,'2021-01-21 11:31:34','2021-01-21 11:38:42',NULL,1,0),
('d60d2926e98147bbaca7529a90bb8547','21fd34b382d844c4a2fe8acdf8ad75f0','alicloud','mysql-1C-1024M','mysql.n1.micro.1',1,1024,NULL,'{}',NULL,NULL,NULL,'2021-01-25 17:58:10','2021-01-25 17:58:10',NULL,1,0),
('f318296a6dc24b0591442932c6f5ded3','73aa4d40248849c48cb0fcde88d1d1d1','tencentcloud','1C-2000M','2000',1,256,NULL,'{}',NULL,NULL,NULL,'2021-01-24 16:53:01','2021-01-24 16:53:01',NULL,1,0);

/*Data for the table `resource` */

insert  into `resource`(`id`,`provider`,`resource_type`,`resource_name`,`extend_info`,`resource_property`,`resource_output`,`data_source_name`,`data_source_argument`,`data_source`,`data_source_output`,`is_locked`,`created_time`,`updated_time`,`deleted_time`,`enabled`,`is_deleted`) values
('074354e0795a4e859cff2c6e7471e6bf','tencentcloud','vpc','tencentcloud_vpc','{\"is_multicast\": false, \"tags\": {\"type\": \"json\"}}','{\"cidr\": {\"convert\": \"cidr_block\", \"allow_null\": 0, \"type\": \"string\"}, \"name\": {\"convert\": \"name\", \"allow_null\": 0, \"type\": \"string\"}}','{\"resource_id\": {\"type\": \"string\", \"value\": \"id\"}}','tencentcloud_vpc_instances','instance_list','{\"resource_id\": \"vpc_id\"}','{\"cidr\": {\"convert\": \"cidr_block\", \"allow_null\": 0, \"type\": \"string\"}, \"name\": {\"convert\": \"name\", \"allow_null\": 0, \"type\": \"string\"}, \"resource_id\": \"vpc_id\"}',0,'2021-03-25 15:39:17','2021-03-25 15:39:17',NULL,1,0),
('0b6f58a4a9764af79bcdb27659dd04f6','tencentcloud','eip_association','tencentcloud_eip_association','{}','{\"instance_id\": {\"convert\": \"instance_id\", \"allow_null\": 0, \"type\": \"string\"}, \"eip_id\": {\"convert\": \"eip_id\", \"allow_null\": 0, \"type\": \"string\"}, \"name\": \"-\", \"private_ip\": {\"convert\": \"private_ip\", \"allow_null\": 1, \"type\": \"string\"}}','{\"resource_id\": \"id\"}','','',NULL,NULL,0,'2021-01-23 17:37:36','2021-01-23 17:37:36',NULL,1,0),
('1276c410c524401c9e37c5cab2add904','tencentcloud','route_table','tencentcloud_route_table','{}','{\"vpc_id\": {\"convert\": \"vpc_id\", \"allow_null\": 0, \"type\": \"string\"}, \"name\": {\"convert\": \"name\", \"allow_null\": 0, \"type\": \"string\"}}','{}','tencentcloud_vpc_route_tables','instance_list','{\"resource_id\": \"route_table_id\"}','{\"vpc_id\": {\"convert\": \"vpc_id\", \"allow_null\": 0, \"type\": \"string\"},\"resource_id\": \"vpc_id\", \"name\": {\"convert\": \"name\", \"allow_null\": 0, \"type\": \"string\"}}',0,'2021-01-13 18:20:01','2021-03-16 11:26:59',NULL,1,0),
('161ba756498c4514893d7b37c83d3daf','tencentcloud','security_group','tencentcloud_security_group','{\"description\": \"from terraform\", \"tags\": {\"type\": \"json\"}}','{\"vpc_id\": \"-\", \"name\": {\"convert\": \"name\", \"allow_null\": 0, \"type\": \"string\"}}','{}','tencentcloud_security_groups','security_groups','{\"resource_id\": \"security_group_id\"}','{\"vpc_id\": \"-\", \"name\": {\"convert\": \"name\", \"allow_null\": 0, \"type\": \"string\"}, \"resource_id\": \"security_group_id\"}',0,'2021-01-14 10:01:20','2021-03-16 11:20:19',NULL,1,0),
('1c9a8a30d3da48d38941509e6149d61e','alicloud','vpc','alicloud_vpc','{\"description\": \"from terraform\", \"tags\": {\"type\": \"json\"}}','{\"cidr\": {\"convert\": \"cidr_block\", \"allow_null\": 0, \"type\": \"string\"}, \"name\": {\"convert\": \"name\", \"allow_null\": 0, \"type\": \"string\"}}','{\"resource_id\": \"id\"}','alicloud_vpcs','vpcs','{\"resource_id\": {\"convert\": \"ids\", \"type\": \"list\"}}','{\"cidr\": {\"convert\": \"cidr_block\", \"allow_null\": 0, \"type\": \"string\"}, \"name\":\"vpc_name\",\"resource_id\": \"id\"}',0,'2021-01-21 17:39:03','2021-01-21 17:39:03',NULL,1,0),
('2440b0e9abaf4ebca78461b1b64324ca','tencentcloud','route_entry','tencentcloud_route_table_entry','{\"description\": \"from terraform\"}','{\"next_hub\": {\"convert\": \"next_hub\", \"allow_null\": 0, \"type\": \"string\"}, \"name\": \"-\", \"destination\": {\"convert\": \"destination_cidr_block\", \"allow_null\": 0, \"type\": \"string\"}, \"next_type\": {\"convert\": \"next_type\", \"allow_null\": 0, \"type\": \"string\"}, \"route_table_id\": {\"convert\": \"route_table_id\", \"allow_null\": 0, \"type\": \"string\"}, \"vpc_id\": \"-\"}','{}','','',NULL,NULL,0,'2021-01-13 20:04:12','2021-01-13 20:04:12',NULL,1,0),
('248cfc042c2d4e3c93e43fceff06016f','tencentcloud','eip','tencentcloud_eip','{}','{\"name\": {\"convert\": \"name\", \"allow_null\": 0, \"type\": \"string\"}}','{\"ipaddress\": \"public_ip\", \"resource_id\": \"id\"}','tencentcloud_eips','eip_list','{\"resource_id\": \"eip_id\"}','{\"name\": {\"convert\": \"name\", \"allow_null\": 0, \"type\": \"string\"}, \"resource_id\": \"eip_id\"}',0,'2021-01-23 17:37:24','2021-03-16 14:47:40',NULL,1,0),
('27d7a534b0274355a3223faf8c3243f7','alicloud','route_entry','alicloud_route_entry','{}','{\"next_hub\": {\"convert\": \"nexthop_id\", \"allow_null\": 0, \"type\": \"string\"}, \"name\": \"name\", \"destination\": {\"convert\": \"destination_cidrblock\", \"allow_null\": 0, \"type\": \"string\"}, \"next_type\": {\"convert\": \"nexthop_type\", \"allow_null\": 0, \"type\": \"string\"}, \"route_table_id\": {\"convert\": \"route_table_id\", \"allow_null\": 0, \"type\": \"string\"}, \"vpc_id\": \"-\"}','{\"resource_id\": \"id\"}','','',NULL,NULL,0,'2021-01-22 15:05:21','2021-01-22 15:05:21',NULL,1,0),
('2aa8cd54f561493a981eae5fbcd0661f','tencentcloud','security_group_rule','tencentcloud_security_group_rule','{\"description\": \"from terraform\"}','{\"cidr_ip\": {\"convert\": \"cidr_ip\", \"allow_null\": 0, \"type\": \"string\"}, \"description\": {\"convert\": \"description\", \"allow_null\": 1, \"type\": \"string\"}, \"security_group_id\": {\"convert\": \"security_group_id\", \"allow_null\": 0, \"type\": \"string\"}, \"policy\": {\"convert\": \"policy\", \"allow_null\": 0, \"type\": \"string\"}, \"vpc_id\": \"-\", \"type\": {\"convert\": \"type\", \"allow_null\": 0, \"type\": \"string\"}, \"ports\": {\"convert\": \"port_range\", \"allow_null\": 0, \"type\": \"string\"}, \"ip_protocol\": {\"convert\": \"ip_protocol\", \"allow_null\": 0, \"type\": \"string\"}}','{}','','',NULL,NULL,0,'2021-01-14 10:48:44','2021-01-14 10:48:44',NULL,1,0),
('2b7a75d4c4c64a6698ceb17859008047','alicloud','disk_attach','alicloud_disk_attachment','{}','{\"instance_id\": {\"convert\": \"instance_id\", \"allow_null\": 0, \"type\": \"string\"}, \"disk_id\": {\"convert\": \"disk_id\", \"allow_null\": 0, \"type\": \"string\"}}','{\"resource_id\": \"id\"}','','',NULL,NULL,0,'2021-01-25 16:20:27','2021-01-25 16:20:27',NULL,1,0),
('3617a570ab344e87be60ce5165680c1d','tencentcloud','network_interface_attach','tencentcloud_eni_attachment','{}','{\"instance_id\": {\"convert\": \"instance_id\", \"allow_null\": 0, \"type\": \"string\"}, \"network_interface_id\": {\"convert\": \"eni_id\", \"allow_null\": 0, \"type\": \"string\"}}','{\"resource_id\": \"id\"}','','',NULL,NULL,0,'2021-01-23 17:37:15','2021-01-23 17:37:15',NULL,1,0),
('39a526c0023e44e8bbbb736c1cd6487c','tencentcloud','subnet','tencentcloud_subnet','{\"is_multicast\": false}','{\"vpc_id\": {\"convert\": \"vpc_id\", \"allow_null\": 0, \"type\": \"string\"}, \"cidr\": {\"convert\": \"cidr_block\", \"allow_null\": 0, \"type\": \"string\"}, \"name\": {\"convert\": \"name\", \"allow_null\": 0, \"type\": \"string\"}, \"zone\": {\"convert\": \"availability_zone\", \"allow_null\": 0, \"type\": \"string\"}}','{}','tencentcloud_vpc_subnets','instance_list','{\"resource_id\": \"subnet_id\"}','{\"resource_id\": \"subnet_id\",\"vpc_id\": {\"convert\": \"vpc_id\", \"allow_null\": 0, \"type\": \"string\"}, \"cidr\": {\"convert\": \"cidr_block\", \"allow_null\": 0, \"type\": \"string\"}, \"name\": {\"convert\": \"name\", \"allow_null\": 0, \"type\": \"string\"}, \"zone\": {\"convert\": \"availability_zone\", \"allow_null\": 0, \"type\": \"string\"}}',0,'2021-01-12 19:11:46','2021-03-16 11:10:44',NULL,1,0),
('3d501a1ca3524c2b8ce61423f053f695','alicloud','mysql','alicloud_db_instance','{\"second_slave_zone\": \"-\", \"first_slave_zone\": \"-\", \"instance_charge_type\":\"Postpaid\"}','{\"engine\": {\"default\": \"MySQL\", \"convert\": \"engine\", \"allow_null\": 1, \"type\": \"string\"}, \"password\": \"-\", \"disk_size\": {\"convert\": \"instance_storage\", \"allow_null\": 0, \"type\": \"string\"}, \"name\": {\"convert\": \"instance_name\", \"allow_null\": 0, \"type\": \"string\"}, \"zone\": \"-\", \"subnet_id\": {\"convert\": \"vswitch_id\", \"allow_null\": 0, \"type\": \"string\"}, \"force_delete\": \"-\", \"security_group_id\": {\"convert\": \"security_group_ids\", \"allow_null\": 1, \"type\": \"list\"}, \"instance_type\": {\"convert\": \"instance_type\", \"allow_null\": 0, \"type\": \"string\"}, \"version\": {\"convert\": \"engine_version\", \"allow_null\": 0, \"type\": \"string\"}, \"user\": \"-\", \"second_slave_zone\": \"-\", \"vpc_id\": \"-\", \"disk_type\": {\"default\": \"local_ssd\", \"convert\": \"db_instance_storage_type\", \"allow_null\": 1, \"type\": \"string\"}, \"port\": \"-\", \"first_slave_zone\": \"-\"}','{\"ipaddress\": \"connection_string\", \"port\": \"port\", \"resource_id\": \"id\"}','alicloud_db_instances','instances','{\"resource_id\": {\"convert\": \"ids\", \"type\": \"list\"}}','{\"engine\": {\"default\": \"MySQL\", \"convert\": \"engine\", \"allow_null\": 1, \"type\": \"string\"}, \"password\": \"-\", \"disk_size\": {\"convert\": \"instance_storage\", \"allow_null\": 0, \"type\": \"string\"}, \"name\": {\"convert\": \"instance_name\", \"allow_null\": 0, \"type\": \"string\"}, \"zone\": \"-\", \"subnet_id\": {\"convert\": \"vswitch_id\", \"allow_null\": 0, \"type\": \"string\"}, \"force_delete\": \"-\", \"security_group_id\": {\"convert\": \"security_group_ids\", \"allow_null\": 1, \"type\": \"list\"}, \"instance_type\": {\"convert\": \"instance_type\", \"allow_null\": 0, \"type\": \"string\"}, \"version\": {\"convert\": \"engine_version\", \"allow_null\": 0, \"type\": \"string\"}, \"user\": \"-\", \"second_slave_zone\": \"-\", \"vpc_id\": \"-\", \"disk_type\": {\"default\": \"local_ssd\", \"convert\": \"db_instance_storage_type\", \"allow_null\": 1, \"type\": \"string\"}, \"ipaddress\": \"connection_string\", \"port\": \"port\", \"first_slave_zone\": \"-\", \"resource_id\": \"id\"}',0,'2021-01-25 20:41:41','2021-03-16 15:05:23',NULL,1,0),
('43ffc20b8cec4cb1ab916ee83ab769b0','tencentcloud','disk','tencentcloud_cbs_storage','{\"encrypt\": {\"type\": \"bool\"}}','{\"type\": {\"default\": \"CLOUD_BASIC\", \"convert\": \"storage_type\", \"allow_null\": 1, \"type\": \"string\"}, \"name\": {\"convert\": \"storage_name\", \"allow_null\": 0, \"type\": \"string\"}, \"zone\": {\"convert\": \"availability_zone\", \"allow_null\": 1, \"type\": \"string\"}, \"size\": {\"convert\": \"storage_size\", \"allow_null\": 1, \"type\": \"int\"}}','{\"resource_id\": \"id\"}','tencentcloud_cbs_storages','storage_list','{\"resource_id\": \"storage_id\"}','{\"type\": {\"default\": \"CLOUD_BASIC\", \"convert\": \"storage_type\", \"allow_null\": 1, \"type\": \"string\"}, \"name\": {\"convert\": \"storage_name\", \"allow_null\": 0, \"type\": \"string\"}, \"zone\": {\"convert\": \"availability_zone\", \"allow_null\": 1, \"type\": \"string\"}, \"size\": {\"convert\": \"storage_size\", \"allow_null\": 1, \"type\": \"int\"}, \"resource_id\": \"storage_id\"}',0,'2021-01-23 17:35:59','2021-03-16 14:49:40',NULL,1,0),
('5d6ddc1579934683b08c82aabb18f2dd','tencentcloud','ccn','tencentcloud_ccn','{\"charge_type\": \"PREPAID\", \"bandwidth_limit_type\": \"INTER_REGION_LIMIT\", \"qos\": \"AG\", \"description\": \"from terraform\"}','{\"name\": {\"convert\": \"name\", \"allow_null\": 0, \"type\": \"string\"}}','{\"resource_id\": \"id\"}','tencentcloud_ccn_instances','instance_list','{\"resource_id\": \"ccn_id\"}','{\"name\": {\"convert\": \"name\", \"allow_null\": 0, \"type\": \"string\"}, \"resource_id\": \"ccn_id\"}',0,'2021-01-24 17:16:53','2021-03-16 14:48:08',NULL,1,0),
('5f55e449191b4a19830ab2e8f11a19d7','alicloud','mysql_account','alicloud_db_account','{\"description\": \"from terraform\"}','{\"mysql_id\": {\"convert\": \"instance_id\", \"allow_null\": 0, \"type\": \"string\"}, \"password\": {\"convert\": \"password\", \"allow_null\": 0, \"type\": \"string\"}, \"name\": {\"convert\": \"name\", \"allow_null\": 0, \"type\": \"string\"}}','{\"resource_id\": \"id\"}','','',NULL,NULL,0,'2021-01-25 16:21:21','2021-01-25 16:21:21',NULL,1,0),
('65eab698bf954edea256fb04127a5ff4','tencentcloud','disk_attach','tencentcloud_cbs_storage_attachment','{}','{\"instance_id\": {\"convert\": \"instance_id\", \"allow_null\": 0, \"type\": \"string\"}, \"disk_id\": {\"convert\": \"storage_id\", \"allow_null\": 0, \"type\": \"string\"}}','{\"resource_id\": \"id\"}','','',NULL,NULL,0,'2021-01-23 17:36:16','2021-01-23 17:36:16',NULL,1,0),
('66ef0458af3c4576a933cfee085acc9f','tencentcloud','ccn_bandwidth','tencentcloud_ccn_bandwidth_limit','{}','{\"dest_region\": {\"convert\": \"dst_region\", \"allow_null\": 1, \"type\": \"string\"}, \"bandwidth\": {\"convert\": \"bandwidth_limit\", \"allow_null\": 1, \"type\": \"string\"}, \"from_region\": {\"convert\": \"region\", \"allow_null\": 1, \"type\": \"string\"}, \"ccn_id\": {\"convert\": \"ccn_id\", \"allow_null\": 0, \"type\": \"string\"}}','{\"resource_id\": \"id\"}','','',NULL,NULL,0,'2021-01-24 16:45:49','2021-01-24 16:45:49',NULL,1,0),
('68b7aceac57640b384383262b010ac1c','tencentcloud','mysql','tencentcloud_mysql_instance','{\"slave_deploy_mode\": 0, \"internet_service\": 0}','{\"engine\": \"-\", \"password\": {\"convert\": \"root_password\", \"allow_null\": 1, \"type\": \"string\"}, \"disk_size\": {\"convert\": \"volume_size\", \"allow_null\": 0, \"type\": \"int\"}, \"name\": {\"convert\": \"instance_name\", \"allow_null\": 0, \"type\": \"string\"}, \"zone\": {\"convert\": \"availability_zone\", \"allow_null\": 1, \"type\": \"string\"}, \"subnet_id\": {\"convert\": \"subnet_id\", \"allow_null\": 0, \"type\": \"string\"}, \"force_delete\": {\"convert\": \"force_delete\", \"allow_null\": 1, \"type\": \"bool\"}, \"security_group_id\": {\"convert\": \"security_groups\", \"allow_null\": 1, \"type\": \"list\"}, \"instance_type\": {\"default\": 256, \"convert\": \"mem_size\", \"allow_null\": 0, \"type\": \"int\"}, \"version\": {\"convert\": \"engine_version\", \"allow_null\": 0, \"type\": \"string\"}, \"user\": \"-\", \"second_slave_zone\": {\"convert\": \"second_slave_zone\", \"allow_null\": 1, \"type\": \"string\"}, \"vpc_id\": {\"convert\": \"vpc_id\", \"allow_null\": 0, \"type\": \"string\"}, \"disk_type\": \"-\", \"port\": {\"default\": 3306, \"convert\": \"intranet_port\", \"allow_null\": 1, \"type\": \"int\"}, \"first_slave_zone\": {\"convert\": \"first_slave_zone\", \"allow_null\": 1, \"type\": \"string\"}}','{\"ipaddress\": \"intranet_ip\", \"port\": \"internet_port\", \"resource_id\": \"id\"}','tencentcloud_mysql_instance','instance_list','{\"resource_id\": \"mysql_id\"}','{\"resource_id\": \"mysql_id\", \"ipaddress\": \"intranet_ip\", \"port\": \"internet_port\", \"engine\": \"-\", \"password\": {\"convert\": \"root_password\", \"allow_null\": 1, \"type\": \"string\"}, \"disk_size\": {\"convert\": \"volume_size\", \"allow_null\": 0, \"type\": \"int\"}, \"name\": {\"convert\": \"instance_name\", \"allow_null\": 0, \"type\": \"string\"}, \"zone\": {\"convert\": \"availability_zone\", \"allow_null\": 1, \"type\": \"string\"}, \"subnet_id\": {\"convert\": \"subnet_id\", \"allow_null\": 0, \"type\": \"string\"}, \"force_delete\": {\"convert\": \"force_delete\", \"allow_null\": 1, \"type\": \"bool\"}, \"security_group_id\": {\"convert\": \"security_groups\", \"allow_null\": 1, \"type\": \"list\"}, \"instance_type\": {\"default\": 256, \"convert\": \"mem_size\", \"allow_null\": 0, \"type\": \"int\"}, \"version\": {\"convert\": \"engine_version\", \"allow_null\": 0, \"type\": \"string\"}, \"user\": \"-\", \"second_slave_zone\": {\"convert\": \"second_slave_zone\", \"allow_null\": 1, \"type\": \"string\"}, \"vpc_id\": {\"convert\": \"vpc_id\", \"allow_null\": 0, \"type\": \"string\"}, \"disk_type\": \"-\", \"port\": {\"default\": 3306, \"convert\": \"intranet_port\", \"allow_null\": 1, \"type\": \"int\"}, \"first_slave_zone\": {\"convert\": \"first_slave_zone\", \"allow_null\": 1, \"type\": \"string\"}}',0,'2021-01-24 19:09:11','2021-03-16 15:05:43',NULL,1,0),
('6c33d867e13141809e6449f600359c6f','alicloud','subnet','alicloud_vswitch','{\"tags\": {\"type\": \"json\"}}','{\"vpc_id\": {\"convert\": \"vpc_id\", \"allow_null\": 0, \"type\": \"string\"}, \"cidr\": {\"convert\": \"cidr_block\", \"allow_null\": 0, \"type\": \"string\"}, \"name\": {\"convert\": \"name\", \"allow_null\": 1, \"type\": \"string\"}, \"zone\": {\"convert\": \"availability_zone\", \"allow_null\": 0, \"type\": \"string\"}}','{\"resource_id\": \"id\"}','alicloud_vswitches','vswitches','{\"resource_id\": {\"convert\": \"ids\", \"type\": \"list\"}}','{\"resource_id\": \"id\",\"vpc_id\": {\"convert\": \"vpc_id\", \"allow_null\": 0, \"type\": \"string\"}, \"cidr\": {\"convert\": \"cidr_block\", \"allow_null\": 0, \"type\": \"string\"}, \"name\": {\"convert\": \"name\", \"allow_null\": 1, \"type\": \"string\"}, \"zone\":\"zone_id\"}',0,'2021-01-21 17:42:45','2021-03-16 11:16:08',NULL,1,0),
('6c8d8a72c6fc4855911aa0f386195ed0','alicloud','disk','alicloud_disk','{\"encrypted\": {\"type\": \"bool\", \"value\": false}, \"description\": \"from terraform\"}','{\"type\": {\"default\": \"cloud_efficiency\", \"convert\": \"category\", \"allow_null\": 1, \"type\": \"string\"}, \"name\": {\"convert\": \"name\", \"allow_null\": 0, \"type\": \"string\"}, \"zone\": {\"convert\": \"availability_zone\", \"allow_null\": 1, \"type\": \"string\"}, \"size\": {\"convert\": \"size\", \"allow_null\": 1, \"type\": \"int\"}}','{\"resource_id\": \"id\"}','alicloud_disks','disks','{\"resource_id\": {\"convert\": \"ids\", \"type\": \"list\"}}','{\"type\": {\"default\": \"cloud_efficiency\", \"convert\": \"category\", \"allow_null\": 1, \"type\": \"string\"}, \"name\": {\"convert\": \"name\", \"allow_null\": 0, \"type\": \"string\"}, \"zone\": {\"convert\": \"availability_zone\", \"allow_null\": 1, \"type\": \"string\"}, \"size\": {\"convert\": \"size\", \"allow_null\": 1, \"type\": \"int\"},\"resource_id\": \"id\"}',0,'2021-01-25 17:14:07','2021-03-16 14:50:09',NULL,1,0),
('818f6c1089b1493294dad141846943b6','alicloud','security_group_rule','alicloud_security_group_rule','{\"description\": \"from terraform\"}','{\"nic_type\": {\"convert\": \"nic_type\", \"allow_null\": 1, \"type\": \"string\"}, \"cidr_ip\": {\"convert\": \"cidr_ip\", \"allow_null\": 0, \"type\": \"string\"}, \"description\": {\"convert\": \"description\", \"allow_null\": 1, \"type\": \"string\"}, \"security_group_id\": {\"convert\": \"security_group_id\", \"allow_null\": 0, \"type\": \"string\"}, \"priority\": {\"convert\": \"priority\", \"allow_null\": 1, \"type\": \"string\"}, \"policy\": {\"convert\": \"policy\", \"allow_null\": 0, \"type\": \"string\"}, \"vpc_id\": \"-\", \"type\": {\"convert\": \"type\", \"allow_null\": 0, \"type\": \"string\"}, \"ports\": {\"convert\": \"port_range\", \"allow_null\": 0, \"type\": \"string\"}, \"ip_protocol\": {\"convert\": \"ip_protocol\", \"allow_null\": 0, \"type\": \"string\"}}','{\"resource_id\": \"id\"}','','',NULL,NULL,0,'2021-01-21 18:20:38','2021-01-21 18:20:38',NULL,1,0),
('9713233c5f974ba898d48912c3577f0b','tencentcloud','mysql_account','tencentcloud_mysql_account','{\"description\": \"from terraform\"}','{\"mysql_id\": {\"convert\": \"mysql_id\", \"allow_null\": 0, \"type\": \"string\"}, \"password\": {\"convert\": \"password\", \"allow_null\": 0, \"type\": \"string\"}, \"name\": {\"convert\": \"name\", \"allow_null\": 0, \"type\": \"string\"}}','{\"resource_id\": \"id\"}','','',NULL,NULL,0,'2021-01-24 19:30:20','2021-01-24 19:30:20',NULL,1,0),
('98de4b1bc5a14c24b54312d4ffaab449','tencentcloud','object_storage','tencentcloud_cos_bucket','{\"tags\": {\"type\": \"json\"}}','{\"name\": {\"convert\": \"bucket\", \"allow_null\": 0, \"type\": \"string\"}, \"acl\": {\"convert\": \"acl\", \"allow_null\": 1, \"type\": \"string\"}}','{\"url\": \"cos_bucket_url\", \"resource_id\": \"id\"}','tencentcloud_cos_buckets','bucket_list','{\"resource_id\": \"bucket_prefix\"}','{\"name\": {\"convert\": \"bucket\", \"allow_null\": 0, \"type\": \"string\"}, \"resource_id\": \"bucket\", \"acl\": {\"convert\": \"acl\", \"allow_null\": 1, \"type\": \"string\"}}',0,'2021-01-22 18:21:42','2021-03-16 14:50:41',NULL,1,0),
('aa40431c787b443ebd6c5618524ec439','alicloud','lb_listener','alicloud_slb_listener','{\"bandwidth\": {\"type\": \"int\"}}','{\"health_check\": {\"convert\": \"health_check\", \"allow_null\": 1, \"type\": \"bool\"}, \"protocol\": {\"default\": \"tcp\", \"convert\": \"protocol\", \"allow_null\": 1, \"type\": \"string\"}, \"name\": \"-\", \"health_check_uri\": {\"convert\": \"health_check_uri\", \"allow_null\": 1, \"type\": \"string\"}, \"lb_id\": {\"convert\": \"load_balancer_id\", \"allow_null\": 0, \"type\": \"string\"}, \"port\": {\"convert\": \"frontend_port\", \"allow_null\": 0, \"type\": \"int\"}, \"backend_port\": {\"convert\": \"backend_port\", \"allow_null\": 0, \"type\": \"int\"}}','{\"resource_id\": \"id\"}','','',NULL,NULL,0,'2021-01-25 17:38:54','2021-01-25 17:38:54',NULL,1,0),
('adf73fdf773f4ca98bced48cb650a181','alicloud','route_table','alicloud_route_table','{\"description\": \"from terraform\"}','{\"vpc_id\": {\"convert\": \"vpc_id\", \"allow_null\": 0, \"type\": \"string\"}, \"name\": {\"convert\": \"name\", \"allow_null\": 0, \"type\": \"string\"}}','{\"resource_id\": \"id\"}','alicloud_route_tables','tables','{\"resource_id\": {\"convert\": \"ids\", \"type\": \"list\"}}','{\"vpc_id\": {\"convert\": \"vpc_id\", \"allow_null\": 0, \"type\": \"string\"},\"resource_id\": \"id\", \"name\": {\"convert\": \"name\", \"allow_null\": 0, \"type\": \"string\"}}',0,'2021-01-21 17:46:20','2021-03-16 11:26:19',NULL,1,0),
('ae0ae0c2eee04ee3804436ea800002d0','alicloud','object_storage','alicloud_oss_bucket','{\"tags\": {\"type\": \"json\"}}','{\"name\": {\"convert\": \"bucket\", \"allow_null\": 0, \"type\": \"string\"}, \"acl\": {\"convert\": \"acl\", \"allow_null\": 1, \"type\": \"string\"}}','{\"url\": \"intranet_endpoint\", \"resource_id\": \"id\"}','alicloud_oss_buckets','buckets','{\"resource_id\": \"name_regex\"}','{\"name\": {\"convert\": \"bucket\", \"allow_null\": 0, \"type\": \"string\"}, \"acl\": {\"convert\": \"acl\", \"allow_null\": 1, \"type\": \"string\"},\"resource_id\": \"name\", \"url\": \"intranet_endpoint\"}',0,'2021-01-25 16:20:04','2021-03-16 14:51:02',NULL,1,0),
('bf4e59a75e5141ff925abe6404ad7636','alicloud','lb_attach','alicloud_slb_backend_server','{}','{\"listener_id\": \"-\", \"weight\": {\"convert\": \"weight\", \"allow_null\": 1, \"type\": \"int\"}, \"lb_id\": {\"convert\": \"load_balancer_id\", \"allow_null\": 0, \"type\": \"string\"}, \"instance_id\": {\"convert\": \"server_id\", \"allow_null\": 1, \"type\": \"string\"}, \"port\": \"-\", \"backend_servers\": {\"convert\": \"backend_servers\", \"allow_null\": 0, \"type\": \"list\"}}','{\"resource_id\": \"id\"}','','',NULL,NULL,0,'2021-01-25 16:20:57','2021-01-25 16:20:57',NULL,1,0),
('cae06aaf5cc743818b164776eb2c9a63','tencentcloud','lb_attach','tencentcloud_clb_attachment','{}','{\"listener_id\": {\"convert\": \"listener_id\", \"allow_null\": 0, \"type\": \"string\"}, \"weight\": {\"convert\": \"weight\", \"allow_null\": 1, \"type\": \"int\"}, \"lb_id\": {\"convert\": \"clb_id\", \"allow_null\": 1, \"type\": \"string\"}, \"instance_id\": {\"convert\": \"instance_id\", \"allow_null\": 1, \"type\": \"string\"}, \"port\": {\"convert\": \"port\", \"allow_null\": 1, \"type\": \"int\"}, \"backend_servers\": {\"convert\": \"targets\", \"allow_null\": 0, \"type\": \"list\"}}','{\"resource_id\": \"id\"}','','',NULL,NULL,0,'2021-01-23 23:13:45','2021-01-23 23:13:45',NULL,1,0),
('cc70229a569c46dda38e64ca848002bf','alicloud','instance','alicloud_instance','{\"system_disk_name\": {\"type\": \"string\"}, \"description\": \"create from terraform\"}','{\"disk_type\": {\"default\": \"cloud_essd\", \"convert\": \"system_disk_category\", \"allow_null\": 0, \"type\": \"string\"}, \"disk_size\": {\"default\": 40, \"convert\": \"system_disk_size\", \"allow_null\": 0, \"type\": \"int\"}, \"name\": {\"convert\": \"instance_name\", \"allow_null\": 0, \"type\": \"string\"}, \"zone\": {\"convert\": \"availability_zone\", \"allow_null\": 0, \"type\": \"string\"}, \"subnet_id\": {\"convert\": \"vswitch_id\", \"allow_null\": 0, \"type\": \"string\"}, \"force_delete\": {\"convert\": \"force_delete\", \"allow_null\": 1, \"type\": \"bool\"}, \"image\": {\"convert\": \"image_id\", \"allow_null\": 0, \"type\": \"string\"}, \"hostname\": {\"convert\": \"host_name\", \"allow_null\": 1, \"type\": \"string\"}, \"security_group_id\": {\"convert\": \"security_groups\", \"allow_null\": 1, \"type\": \"list\"}, \"instance_type\": {\"convert\": \"instance_type\", \"allow_null\": 0, \"type\": \"string\"}, \"vpc_id\": \"-\", \"password\": {\"convert\": \"password\", \"allow_null\": 0, \"type\": \"string\"}, \"power_action\": {\"convert\": \"status\", \"allow_null\": 1, \"type\": \"string\"}, \"data_disks\": {\"convert\": \"data_disks\", \"allow_null\": 1, \"type\": \"json\"}}','{\"public_ip\": \"public_ip\", \"ipaddress\": \"private_ip\", \"resource_id\": \"id\"}','alicloud_instances','instances','{\"resource_id\": {\"convert\": \"ids\", \"type\": \"list\"}}','{\"disk_type\": {\"default\": \"cloud_essd\", \"convert\": \"system_disk_category\", \"allow_null\": 0, \"type\": \"string\"}, \"disk_size\": {\"default\": 40, \"convert\": \"system_disk_size\", \"allow_null\": 0, \"type\": \"int\"}, \"name\": {\"convert\": \"instance_name\", \"allow_null\": 0, \"type\": \"string\"}, \"zone\": {\"convert\": \"availability_zone\", \"allow_null\": 0, \"type\": \"string\"}, \"subnet_id\": {\"convert\": \"vswitch_id\", \"allow_null\": 0, \"type\": \"string\"}, \"force_delete\": {\"convert\": \"force_delete\", \"allow_null\": 1, \"type\": \"bool\"}, \"image\": {\"convert\": \"image_id\", \"allow_null\": 0, \"type\": \"string\"}, \"hostname\": {\"convert\": \"host_name\", \"allow_null\": 1, \"type\": \"string\"}, \"security_group_id\": {\"convert\": \"security_groups\", \"allow_null\": 1, \"type\": \"list\"}, \"instance_type\": {\"convert\": \"instance_type\", \"allow_null\": 0, \"type\": \"string\"}, \"vpc_id\": \"-\", \"password\": {\"convert\": \"password\", \"allow_null\": 0, \"type\": \"string\"}, \"power_action\": {\"convert\": \"status\", \"allow_null\": 1, \"type\": \"string\"}, \"data_disks\": {\"convert\": \"data_disks\", \"allow_null\": 1, \"type\": \"json\"}, \"public_ip\": \"public_ip\", \"ipaddress\": \"private_ip\", \"resource_id\": \"id\"}',0,'2021-01-25 16:19:54','2021-03-16 15:06:19',NULL,1,0),
('cd96fd53ee8b421fa8549103abe2d5e6','tencentcloud','instance','tencentcloud_instance','{\"tags\": {\"type\": \"json\"}}','{\"disk_type\": {\"convert\": \"system_disk_type\", \"allow_null\": 0, \"type\": \"string\"}, \"disk_size\": {\"convert\": \"system_disk_size\", \"allow_null\": 0, \"type\": \"string\"}, \"name\": {\"convert\": \"instance_name\", \"allow_null\": 0, \"type\": \"string\"}, \"zone\": {\"convert\": \"availability_zone\", \"allow_null\": 0, \"type\": \"string\"}, \"subnet_id\": {\"convert\": \"subnet_id\", \"allow_null\": 0, \"type\": \"string\"}, \"force_delete\": {\"convert\": \"force_delete\", \"allow_null\": 1, \"type\": \"bool\"}, \"image\": {\"convert\": \"image_id\", \"allow_null\": 0, \"type\": \"string\"}, \"hostname\": {\"convert\": \"hostname\", \"allow_null\": 0, \"type\": \"string\"}, \"security_group_id\": {\"convert\": \"security_groups\", \"allow_null\": 1, \"type\": \"list\"}, \"instance_type\": {\"convert\": \"instance_type\", \"allow_null\": 0, \"type\": \"string\"}, \"vpc_id\": {\"convert\": \"vpc_id\", \"allow_null\": 0, \"type\": \"string\"}, \"password\": {\"convert\": \"password\", \"allow_null\": 0, \"type\": \"string\"}, \"power_action\": {\"convert\": \"running_flag\", \"allow_null\": 1, \"type\": \"bool\"}, \"data_disks\": {\"convert\": \"data_disks\", \"allow_null\": 1, \"type\": \"json\"}}','{\"public_ip\": \"public_ip\", \"ipaddress\": \"private_ip\", \"resource_id\": \"id\"}','tencentcloud_instances','instance_list','{\"resource_id\": \"instance_id\"}','{\"resource_id\": \"instance_id\", \"public_ip\": \"public_ip\", \"ipaddress\": \"private_ip\", \"disk_type\": {\"convert\": \"system_disk_type\", \"allow_null\": 0, \"type\": \"string\"}, \"disk_size\": {\"convert\": \"system_disk_size\", \"allow_null\": 0, \"type\": \"string\"}, \"name\": {\"convert\": \"instance_name\", \"allow_null\": 0, \"type\": \"string\"}, \"zone\": {\"convert\": \"availability_zone\", \"allow_null\": 0, \"type\": \"string\"}, \"subnet_id\": {\"convert\": \"subnet_id\", \"allow_null\": 0, \"type\": \"string\"}, \"force_delete\": {\"convert\": \"force_delete\", \"allow_null\": 1, \"type\": \"bool\"}, \"image\": {\"convert\": \"image_id\", \"allow_null\": 0, \"type\": \"string\"}, \"hostname\": {\"convert\": \"hostname\", \"allow_null\": 0, \"type\": \"string\"}, \"security_group_id\": {\"convert\": \"security_groups\", \"allow_null\": 1, \"type\": \"list\"}, \"instance_type\": {\"convert\": \"instance_type\", \"allow_null\": 0, \"type\": \"string\"}, \"vpc_id\": {\"convert\": \"vpc_id\", \"allow_null\": 0, \"type\": \"string\"}, \"password\": {\"convert\": \"password\", \"allow_null\": 0, \"type\": \"string\"}, \"power_action\": {\"convert\": \"running_flag\", \"allow_null\": 1, \"type\": \"bool\"}, \"data_disks\": {\"convert\": \"data_disks\", \"allow_null\": 1, \"type\": \"json\"}}',0,'2021-01-22 17:25:36','2021-03-16 15:06:35',NULL,1,0),
('ce87aefd26f243f2b4e0fbee4823d1b9','alicloud','mysql_database','alicloud_db_database','{\"description\": \"from terraform\"}','{\"mysql_id\": {\"convert\": \"instance_id\", \"allow_null\": 0, \"type\": \"string\"}, \"name\": {\"convert\": \"name\", \"allow_null\": 0, \"type\": \"string\"}}','{\"resource_id\": \"id\"}','','',NULL,NULL,0,'2021-01-25 21:08:30','2021-01-25 21:08:30',NULL,1,0),
('da1c168374ae4dbc9fabf889630355be','tencentcloud','lb','tencentcloud_clb_instance','{\"tags\": {\"type\": \"json\"}}','{\"subnet_id\": {\"convert\": \"subnet_id\", \"allow_null\": 0, \"type\": \"string\"}, \"vpc_id\": {\"convert\": \"vpc_id\", \"allow_null\": 0, \"type\": \"string\"}, \"name\": {\"convert\": \"clb_name\", \"allow_null\": 0, \"type\": \"string\"}, \"network_type\": {\"default\": \"INTERNAL\", \"convert\": \"network_type\", \"allow_null\": 1, \"type\": \"string\"}}','{\"ipaddress\": \"clb_vips\", \"resource_id\": \"id\"}','tencentcloud_clb_instances','clb_list','{\"resource_id\": \"clb_id\"}','{\"ipaddress\": \"clb_vips\", \"resource_id\": \"clb_id\", \"subnet_id\": {\"convert\": \"subnet_id\", \"allow_null\": 0, \"type\": \"string\"}, \"vpc_id\": {\"convert\": \"vpc_id\", \"allow_null\": 0, \"type\": \"string\"}, \"name\": {\"convert\": \"clb_name\", \"allow_null\": 0, \"type\": \"string\"}, \"network_type\": {\"default\": \"INTERNAL\", \"convert\": \"network_type\", \"allow_null\": 1, \"type\": \"string\"}}',0,'2021-01-23 17:38:33','2021-03-16 14:48:40',NULL,1,0),
('dd15c84a54434f6685b9ae560b9121c2','tencentcloud','network_interface','tencentcloud_eni','{\"ipv4_count\": 1, \"description\": \"create from terraform\"}','{\"subnet_id\": {\"convert\": \"subnet_id\", \"allow_null\": 0, \"type\": \"string\"}, \"vpc_id\": {\"convert\": \"vpc_id\", \"allow_null\": 0, \"type\": \"string\"}, \"ipaddress\": {\"convert\": \"ipv4s\", \"allow_null\": 1, \"type\": \"string\"}, \"name\": {\"convert\": \"name\", \"allow_null\": 0, \"type\": \"string\"}, \"security_group_id\": {\"convert\": \"storage_id\", \"allow_null\": 1, \"type\": \"list\"}}','{\"ipaddress\": \"ipv4_info.0.ip\", \"resource_id\": \"id\"}','tencentcloud_enis','enis','{\"resource_id\": {\"convert\": \"ids\", \"type\": \"list\"}}','{\"ipaddress\": \"ipv4_info.0.ip\", \"resource_id\": \"id\", \"subnet_id\": {\"convert\": \"subnet_id\", \"allow_null\": 0, \"type\": \"string\"}, \"vpc_id\": {\"convert\": \"vpc_id\", \"allow_null\": 0, \"type\": \"string\"}, \"ipaddress\": {\"convert\": \"ipv4s\", \"allow_null\": 1, \"type\": \"string\"}, \"name\": {\"convert\": \"name\", \"allow_null\": 0, \"type\": \"string\"}, \"security_group_id\": {\"convert\": \"storage_id\", \"allow_null\": 1, \"type\": \"list\"}}',0,'2021-01-23 22:47:46','2021-01-23 22:47:46',NULL,1,0),
('dff77ee8e0794c07bcde4eb6df88ba9e','tencentcloud','lb_listener','tencentcloud_clb_listener','{}','{\"health_check\": {\"convert\": \"health_check_switch\", \"allow_null\": 1, \"type\": \"bool\"}, \"protocol\": {\"default\": \"HTTP\", \"convert\": \"protocol\", \"allow_null\": 1, \"type\": \"string\"}, \"name\": {\"convert\": \"listener_name\", \"allow_null\": 0, \"type\": \"string\"}, \"health_check_uri\": {\"convert\": \"health_check_http_path\", \"allow_null\": 1, \"type\": \"string\"}, \"lb_id\": {\"convert\": \"clb_id\", \"allow_null\": 0, \"type\": \"string\"}, \"port\": {\"convert\": \"port\", \"allow_null\": 0, \"type\": \"int\"}, \"backend_port\": \"-\"}','{\"resource_id\": \"listener_id\"}','','',NULL,NULL,0,'2021-01-23 23:26:35','2021-01-23 23:26:35',NULL,1,0),
('e43bbc476ee946faa1bc1cd845ef33d4','tencentcloud','ccn_attach','tencentcloud_ccn_attachment','{}','{\"instance_id\": {\"convert\": \"instance_id\", \"allow_null\": 0, \"type\": \"string\"}, \"instance_type\": {\"default\": \"VPC\", \"convert\": \"instance_type\", \"allow_null\": 1, \"type\": \"string\"}, \"ccn_id\": {\"convert\": \"ccn_id\", \"allow_null\": 0, \"type\": \"string\"}, \"instance_region\": {\"convert\": \"instance_region\", \"allow_null\": 0, \"type\": \"string\"}}','{\"resource_id\": \"id\"}','','',NULL,NULL,0,'2021-01-24 16:45:38','2021-01-24 16:45:38',NULL,1,0),
('f57dc968c5b347a09fac9cbedad342c5','alicloud','security_group','alicloud_security_group','{\"description\": \"from terraform\", \"tags\": {\"type\": \"json\"}}','{\"vpc_id\": {\"convert\": \"vpc_id\", \"allow_null\": 0, \"type\": \"string\"}, \"name\": {\"convert\": \"name\", \"allow_null\": 0, \"type\": \"string\"}}','{\"resource_id\": \"id\"}','alicloud_security_groups','groups','{\"resource_id\": {\"convert\": \"ids\", \"type\": \"list\"}}','{\"vpc_id\": {\"convert\": \"vpc_id\", \"allow_null\": 0, \"type\": \"string\"}, \"name\": {\"convert\": \"name\", \"allow_null\": 0, \"type\": \"string\"}, \"resource_id\": \"id\"}',0,'2021-01-21 17:56:01','2021-03-16 11:19:32',NULL,1,0),
('f69c2785bfd94d0aab5455dc42dbab0d','alicloud','lb','alicloud_slb','{\"specification\": {\"type\": \"string\", \"value\": \"slb.s1.small\"}, \"tags\": {\"type\": \"json\"}}','{\"subnet_id\": {\"convert\": \"vswitch_id\", \"allow_null\": 0, \"type\": \"string\"}, \"vpc_id\": \"-\", \"name\": {\"convert\": \"name\", \"allow_null\": 0, \"type\": \"string\"}, \"network_type\": {\"default\": \"intranet\", \"convert\": \"address_type\", \"allow_null\": 1, \"type\": \"string\"}}','{\"ipaddress\": \"address\", \"resource_id\": \"id\"}','alicloud_slb','slbs','{\"resource_id\": {\"convert\": \"ids\", \"type\": \"list\"}}','{\"subnet_id\": {\"convert\": \"vswitch_id\", \"allow_null\": 0, \"type\": \"string\"}, \"vpc_id\": \"-\", \"name\": {\"convert\": \"name\", \"allow_null\": 0, \"type\": \"string\"}, \"network_type\": {\"default\": \"intranet\", \"convert\": \"address_type\", \"allow_null\": 1, \"type\": \"string\"}, \"resource_id\": \"id\", \"ipaddress\": \"address\"}',0,'2021-01-25 17:21:10','2021-03-16 14:49:07',NULL,1,0);


